param(
    [Parameter(Mandatory = $true)]
    [ValidateSet("docker", "podman")]
    [string] $Engine,

    [Parameter(Mandatory = $true)]
    [ValidateSet("off", "auto", "on")]
    [string] $Gpu,

    [Parameter(Mandatory = $true)]
    [ValidateRange(1, 65535)]
    [int] $AppPort,

    [Parameter(Mandatory = $true)]
    [string] $PackageFlavor,

    [Parameter(Mandatory = $true)]
    [ValidatePattern("^[a-f0-9]{32}$")]
    [string] $HelperSessionId,

    [Parameter(Mandatory = $true)]
    [ValidatePattern("^[a-f0-9]{32}$")]
    [string] $OperationId,

    [Parameter(Mandatory = $true)]
    [ValidateSet("google", "azure")]
    [string] $Provider
)

$ErrorActionPreference = "Stop"
. "$PSScriptRoot\lib\TowerScoutHostHelper.ps1"

$packageRoot = (Resolve-Path -LiteralPath (Join-Path $PSScriptRoot "..")).Path
$profile = New-TowerScoutHostHelperRuntimeProfile `
    -Engine $Engine `
    -Gpu $Gpu `
    -AppPort $AppPort `
    -PackageRoot $packageRoot `
    -PackageFlavor $PackageFlavor `
    -HelperSessionId $HelperSessionId `
    -ProviderTlsRepairEnabled:$true
$sessionPath = Join-Path `
    (Get-TowerScoutHostHelperStateDirectory -RootPath $packageRoot) `
    ("session-{0}.json" -f $HelperSessionId)
Set-TowerScoutHostHelperObjectValue `
    -InputObject $profile `
    -Name "SessionPath" `
    -Value $sessionPath

if (-not (Test-TowerScoutHostHelperSessionActive -Profile $profile)) {
    throw "The TowerScout host-helper session is no longer active."
}

$plan = New-TowerScoutProviderTlsRepairOperationPlan `
    -Profile $profile `
    -Provider $Provider `
    -Confirmation $script:TowerScoutHostHelperProviderTlsRepairConfirmation
if (-not [bool] $plan.Accepted -or $plan.OperationId -ne $OperationId) {
    # The operation id is intentionally generated by the listener. Rebuild the
    # allowlisted plan while preserving only that already-recorded identifier.
    if (-not [bool] $plan.Accepted) {
        throw "The TowerScout host-helper operation plan could not be reconstructed."
    }
    Set-TowerScoutHostHelperObjectValue `
        -InputObject $plan `
        -Name "OperationId" `
        -Value $OperationId
}

Invoke-TowerScoutProviderTlsRepairControlledExecution `
    -Profile $profile `
    -Plan $plan `
    -ExecutionEnabled:$true | Out-Null
