#!/usr/bin/env node
/**
 * TowerScout Build Script - Frontend Refactoring (TASK-038)
 * 
 * Strategy: Concatenate modular source files → overwrite towerscout.js
 * Serving: Flask route /js/<path:path> serves overwritten towerscout.js
 * 
 * Usage:
 *   node webapp/build.js          # Standard build
 *   node webapp/build.js --watch  # Watch mode (future)
 */

const fs = require('fs');
const path = require('path');

// Configuration
const WEBAPP_DIR = __dirname;
const JS_DIR = path.join(WEBAPP_DIR, 'js');
const SRC_DIR = path.join(JS_DIR, 'src');
const OUTPUT_FILE = path.join(JS_DIR, 'towerscout.js');
const BACKUP_FILE = path.join(JS_DIR, 'towerscout.original.js');

// Strict dependency order (CRITICAL - load order matters)
const MODULE_ORDER = [
    // Stage 1: Foundation (must load first)
    'src/config.js',
    'src/store.js',
    'src/managers/ProviderStateManager.js',
    'src/managers/TimerManager.js',
    'src/managers/EventListenerManager.js',
    'src/managers/ErrorHandler.js',

    // Stage 2: Boundaries
    'src/boundaries/CircleBoundary.js',
    'src/boundaries/PolygonBoundary.js',
    'src/boundaries/ZipcodeBoundary.js',

    // Stage 3: Providers (TSMap base must load before implementations)
    'src/providers/TSMap_base.js',
    'src/providers/GoogleMap.js',
    'src/providers/AzureMap.js',
    'src/providers/providerInit.js',
    'src/providers/providerSwitch.js',

    // Stage 4: Detection (PlaceRect must load first as base class)
    'src/detection/PlaceRect.js',
    'src/detection/Detection.js',
    'src/detection/Tile.js',
    'src/detection/DetectionList.js',
    'src/detection/DetectionReview.js',

    // Stage 5: UI & Utils
    'src/ui/search.js',
    'src/ui/export.js',
    'src/ui/navigation.js',
    'src/utils/coordinates.js',
    'src/utils/imagery.js',
    'src/utils/apiHelpers.js',

    // MUST LOAD AFTER ALL CLASSES (exposes to window)
    'src/globals.js',

    // MUST LOAD LAST (initialization code)
    'src/towerscout.js'
];

/**
 * Backup original towerscout.js before first build
 */
function backupOriginal() {
    if (fs.existsSync(OUTPUT_FILE) && !fs.existsSync(BACKUP_FILE)) {
        console.log('📦 Backing up original towerscout.js...');
        fs.copyFileSync(OUTPUT_FILE, BACKUP_FILE);
        const stats = fs.statSync(BACKUP_FILE);
        console.log(`   ✅ Backup created: ${(stats.size / 1024).toFixed(1)} KB`);
        console.log(`   📁 Location: ${path.relative(process.cwd(), BACKUP_FILE)}`);
    } else if (fs.existsSync(BACKUP_FILE)) {
        console.log('✅ Original backup already exists');
    } else {
        console.log('⚠️  No existing towerscout.js to backup (fresh start)');
    }
}

/**
 * Build bundle by concatenating modules in dependency order
 */
function buildBundle() {
    console.log('\n🔨 Building TowerScout bundle...');
    console.log(`   📂 Source: ${path.relative(process.cwd(), JS_DIR)}`);
    console.log(`   📄 Output: ${path.relative(process.cwd(), OUTPUT_FILE)}`);
    console.log('');

    // Bundle header
    let bundle = '/**\n';
    bundle += ' * TowerScout Frontend Bundle - Auto-generated\n';
    bundle += ` * Build Date: ${new Date().toISOString()}\n`;
    bundle += ' * Build Script: webapp/build.js\n';
    bundle += ' * \n';
    bundle += ' * ⚠️  DO NOT EDIT THIS FILE DIRECTLY\n';
    bundle += ' * Modify source files in webapp/js/src/ directory\n';
    bundle += ' * Then rebuild: node webapp/build.js\n';
    bundle += ' */\n\n';

    let totalSize = 0;
    const missingFiles = [];

    // Concatenate all modules
    for (const modulePath of MODULE_ORDER) {
        const fullPath = path.join(JS_DIR, modulePath);
        const displayPath = modulePath;

        if (!fs.existsSync(fullPath)) {
            console.log(`   ❌ MISSING: ${displayPath}`);
            missingFiles.push(modulePath);
            continue;
        }

        const content = fs.readFileSync(fullPath, 'utf8');
        const size = (content.length / 1024).toFixed(1);
        totalSize += content.length;

        console.log(`   ✅ ${displayPath} (${size} KB)`);

        // Add module separator and content
        bundle += `\n// ═══════════════════════════════════════════════════════════════════\n`;
        bundle += `// MODULE: ${modulePath}\n`;
        bundle += `// ═══════════════════════════════════════════════════════════════════\n\n`;
        bundle += content;
        bundle += '\n';
    }

    // Handle missing files
    if (missingFiles.length > 0) {
        console.error('\n❌ BUILD FAILED: Missing source files');
        console.error('   The following modules are required but not found:');
        missingFiles.forEach(file => console.error(`   - ${file}`));
        console.error('\n   Create these files or remove them from MODULE_ORDER');
        process.exit(1);
    }

    // Write bundle
    fs.writeFileSync(OUTPUT_FILE, bundle, 'utf8');

    const finalSize = (totalSize / 1024).toFixed(1);
    console.log('');
    console.log(`✅ Bundle created successfully`);
    console.log(`   📦 Total size: ${finalSize} KB`);
    console.log(`   📝 Modules: ${MODULE_ORDER.length}`);
    console.log(`   📄 Output: ${path.relative(process.cwd(), OUTPUT_FILE)}`);
    console.log('');
    console.log('🚀 Bundle ready to serve via Flask route /js/towerscout.js');
}

/**
 * Main build process
 */
function main() {
    console.log('═══════════════════════════════════════════════════════════════════');
    console.log('  TowerScout Build System - TASK-038 Frontend Refactoring');
    console.log('═══════════════════════════════════════════════════════════════════');

    try {
        backupOriginal();
        buildBundle();
        console.log('═══════════════════════════════════════════════════════════════════\n');
        process.exit(0);
    } catch (error) {
        console.error('\n❌ BUILD ERROR:', error.message);
        console.error(error.stack);
        process.exit(1);
    }
}

// Run build if executed directly
if (require.main === module) {
    main();
}

module.exports = { buildBundle, backupOriginal };
